spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
  messages:
    basename: i18n/messages

comment:
  avatar: /images/avatar.png